sendsigns:
Messages:
  In-Game: '&7[&4Lobby&7] &4This game has already started! Please try another sign!'
  Full: '&7[&4Lobby&7] &4To be able to join full servers purchase VIP from our website!'
  Restarting: '&7[&4Lobby&7] &4This game is restarting! Please try another sign'
